// Created by iWeb 3.0.4 local-build-20110916

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Consulting_Services___Our_Services___Introduction_files/Consulting_Services___Our_Services___IntroductionMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');fixAllIEPNGs('Media/transparent.gif');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_4','0');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_7','0');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_7','1');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_7','2');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_7','3');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_7','4');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_8','0');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_8','1');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_8','2');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_8','3');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_8','4');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_12','0');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_14','0');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_16','0');IMpreload('Consulting_Services___Our_Services___Introduction_files','shapeimage_18','0');applyEffects()}
