// Created by iWeb 3.0.4 local-build-20110916

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,200),url:'About_Us___Strategic_Partners_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'About_Us___Strategic_Partners_files/stroke_1.png'},{rect:new IWRect(1,-1,209,2),url:'About_Us___Strategic_Partners_files/stroke_2.png'},{rect:new IWRect(210,-1,3,2),url:'About_Us___Strategic_Partners_files/stroke_3.png'},{rect:new IWRect(210,1,3,200),url:'About_Us___Strategic_Partners_files/stroke_4.png'},{rect:new IWRect(210,201,3,3),url:'About_Us___Strategic_Partners_files/stroke_5.png'},{rect:new IWRect(1,201,209,3),url:'About_Us___Strategic_Partners_files/stroke_6.png'},{rect:new IWRect(-1,201,2,3),url:'About_Us___Strategic_Partners_files/stroke_7.png'}],new IWSize(211,203))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('About_Us___Strategic_Partners_files/About_Us___Strategic_PartnersMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');fixAllIEPNGs('Media/transparent.gif');IMpreload('About_Us___Strategic_Partners_files','shapeimage_5','0');IMpreload('About_Us___Strategic_Partners_files','shapeimage_5','1');IMpreload('About_Us___Strategic_Partners_files','shapeimage_5','2');IMpreload('About_Us___Strategic_Partners_files','shapeimage_5','3');IMpreload('About_Us___Strategic_Partners_files','shapeimage_5','4');IMpreload('About_Us___Strategic_Partners_files','shapeimage_6','0');IMpreload('About_Us___Strategic_Partners_files','shapeimage_6','1');IMpreload('About_Us___Strategic_Partners_files','shapeimage_6','2');IMpreload('About_Us___Strategic_Partners_files','shapeimage_6','3');IMpreload('About_Us___Strategic_Partners_files','shapeimage_6','4');applyEffects()}
