// Created by iWeb 3.0.4 local-build-20110916

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,230),url:'Client_Industries___Hospitality_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Client_Industries___Hospitality_files/stroke_1.png'},{rect:new IWRect(1,-1,287,2),url:'Client_Industries___Hospitality_files/stroke_2.png'},{rect:new IWRect(288,-1,2,2),url:'Client_Industries___Hospitality_files/stroke_3.png'},{rect:new IWRect(288,1,2,230),url:'Client_Industries___Hospitality_files/stroke_4.png'},{rect:new IWRect(288,231,2,2),url:'Client_Industries___Hospitality_files/stroke_5.png'},{rect:new IWRect(1,231,287,2),url:'Client_Industries___Hospitality_files/stroke_6.png'},{rect:new IWRect(-1,231,2,2),url:'Client_Industries___Hospitality_files/stroke_7.png'}],new IWSize(289,232)),stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Client_Industries___Hospitality_files/Client_Industries___HospitalityMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');fixAllIEPNGs('Media/transparent.gif');IMpreload('Client_Industries___Hospitality_files','shapeimage_5','0');IMpreload('Client_Industries___Hospitality_files','shapeimage_5','1');IMpreload('Client_Industries___Hospitality_files','shapeimage_5','2');IMpreload('Client_Industries___Hospitality_files','shapeimage_5','3');IMpreload('Client_Industries___Hospitality_files','shapeimage_5','4');IMpreload('Client_Industries___Hospitality_files','shapeimage_6','0');IMpreload('Client_Industries___Hospitality_files','shapeimage_6','1');IMpreload('Client_Industries___Hospitality_files','shapeimage_6','2');IMpreload('Client_Industries___Hospitality_files','shapeimage_6','3');IMpreload('Client_Industries___Hospitality_files','shapeimage_6','4');applyEffects()}
