// Created by iWeb 3.0.4 local-build-20110916

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,200),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke_1.png'},{rect:new IWRect(1,-1,209,2),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke_2.png'},{rect:new IWRect(210,-1,3,2),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke_3.png'},{rect:new IWRect(210,1,3,200),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke_4.png'},{rect:new IWRect(210,201,3,3),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke_5.png'},{rect:new IWRect(1,201,209,3),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke_6.png'},{rect:new IWRect(-1,201,2,3),url:'Consulting_Services___Our_Services___Pilot_Projects_files/stroke_7.png'}],new IWSize(211,203)),stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Consulting_Services___Our_Services___Pilot_Projects_files/Consulting_Services___Our_Services___Pilot_ProjectsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');fixAllIEPNGs('Media/transparent.gif');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_4','0');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_7','0');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_7','1');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_7','2');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_7','3');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_7','4');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_8','0');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_8','1');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_8','2');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_8','3');IMpreload('Consulting_Services___Our_Services___Pilot_Projects_files','shapeimage_8','4');applyEffects()}
