// Created by iWeb 3.0.4 local-build-20110916

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWEmptyStroke(),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,234),url:'XTRA_Welcome_GRAPHICS_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'XTRA_Welcome_GRAPHICS_files/stroke_1.png'},{rect:new IWRect(2,-2,531,4),url:'XTRA_Welcome_GRAPHICS_files/stroke_2.png'},{rect:new IWRect(533,-2,4,4),url:'XTRA_Welcome_GRAPHICS_files/stroke_3.png'},{rect:new IWRect(533,2,4,234),url:'XTRA_Welcome_GRAPHICS_files/stroke_4.png'},{rect:new IWRect(533,236,4,4),url:'XTRA_Welcome_GRAPHICS_files/stroke_5.png'},{rect:new IWRect(2,236,531,4),url:'XTRA_Welcome_GRAPHICS_files/stroke_6.png'},{rect:new IWRect(-2,236,4,4),url:'XTRA_Welcome_GRAPHICS_files/stroke_7.png'}],new IWSize(535,238))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('XTRA_Welcome_GRAPHICS_files/XTRA_Welcome_GRAPHICSMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');fixAllIEPNGs('Media/transparent.gif');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_12','0');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_12','1');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_12','2');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_12','3');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_12','4');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_13','0');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_13','1');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_13','2');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_13','3');IMpreload('XTRA_Welcome_GRAPHICS_files','shapeimage_13','4');applyEffects()}
