// Created by iWeb 3.0.4 local-build-20110916

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,177),url:'Client_Industries___Retail_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Client_Industries___Retail_files/stroke_1.png'},{rect:new IWRect(1,-1,184,2),url:'Client_Industries___Retail_files/stroke_2.png'},{rect:new IWRect(185,-1,3,2),url:'Client_Industries___Retail_files/stroke_3.png'},{rect:new IWRect(185,1,3,177),url:'Client_Industries___Retail_files/stroke_4.png'},{rect:new IWRect(185,178,3,2),url:'Client_Industries___Retail_files/stroke_5.png'},{rect:new IWRect(1,178,184,2),url:'Client_Industries___Retail_files/stroke_6.png'},{rect:new IWRect(-1,178,2,2),url:'Client_Industries___Retail_files/stroke_7.png'}],new IWSize(186,179))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Client_Industries___Retail_files/Client_Industries___RetailMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');fixAllIEPNGs('Media/transparent.gif');IMpreload('Client_Industries___Retail_files','shapeimage_5','0');IMpreload('Client_Industries___Retail_files','shapeimage_5','1');IMpreload('Client_Industries___Retail_files','shapeimage_5','2');IMpreload('Client_Industries___Retail_files','shapeimage_5','3');IMpreload('Client_Industries___Retail_files','shapeimage_5','4');IMpreload('Client_Industries___Retail_files','shapeimage_6','0');IMpreload('Client_Industries___Retail_files','shapeimage_6','1');IMpreload('Client_Industries___Retail_files','shapeimage_6','2');IMpreload('Client_Industries___Retail_files','shapeimage_6','3');IMpreload('Client_Industries___Retail_files','shapeimage_6','4');applyEffects()}
